apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-api
  labels:
    app: sensor-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sensor-api
  template:
    metadata:
      labels:
        app: sensor-api
    spec:
      containers:
      - name: api
        image: sensor-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          value: postgresql://sensor_user:sensor_pass@postgres:5432/sensor_db
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: sensor-api
spec:
  type: LoadBalancer
  selector:
    app: sensor-api
  ports:
  - port: 8000
    targetPort: 8000
